### Carga diaria de Analisis de Sentimientos

*  Cargar los datos
 * Cargar TRM Historica y calcular deltas
*  Calcular correlaciones spearman y pearson
 * Correlaciones con diferentes Lags hasta 15 días
* Validar otras variables

In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option("display.max_columns", None)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [3]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

## Carga de los datos

In [4]:
#TRM = 'TRM2020.csv'
trm_df=pd.read_csv('TRM2020.csv', sep=';',encoding = "ISO-8859-1", engine='python', decimal=",")

In [5]:
trm_df.head()

,Fecha,fecha_Operación,TRM,Diferencia,Dia sem,nom Dia Sem,fin Semana,Dif Cero,date
0,31/05/2020,30/05/2020,3718.82,0.00,7,sáb,1,1,2020-05-30
1,1/06/2020,31/05/2020,3718.82,0.00,1,dom,1,1,2020-05-31
2,2/06/2020,1/06/2020,3716.35,-2.47,2,lun,0,0,2020-06-01
3,3/06/2020,2/06/2020,3651.42,-64.93,3,mar,0,0,2020-06-02
4,4/06/2020,3/06/2020,3588.89,-62.53,4,mié,0,0,2020-06-03

In [6]:
df_Rss = pd.read_excel (r'backupT.xlsx', sheet_name='Hoja3')

In [7]:
df_Rss.head()

,fuenteRss,idP,date,polaridad
0,http://www.nytimes.com/services/xml/rss/nyt/Wo...,https://www.nytimes.com/2020/10/09/world/canad...,2020-10-09 20:08:40,0.00
1,http://www.nytimes.com/services/xml/rss/nyt/Wo...,https://www.nytimes.com/2020/10/09/world/event...,2020-10-09 17:09:08,0.00
2,http://www.nytimes.com/services/xml/rss/nyt/Wo...,https://www.nytimes.com/2020/10/08/briefing/sw...,2020-10-09 05:36:50,0.00
3,http://www.nytimes.com/services/xml/rss/nyt/Wo...,https://www.nytimes.com/2020/10/08/briefing/in...,2020-10-08 20:04:37,0.00
4,http://www.nytimes.com/services/xml/rss/nyt/Wo...,https://www.nytimes.com/2020/10/08/world/brazi...,2020-10-08 20:57:27,0.00

In [8]:
df_Base_Rss = pd.read_excel (r'backupT.xlsx', sheet_name='Hoja1')

In [9]:
df_Base_Rss.head()

,id,FuentesRSS,lenguaje,Fuente,Pais,tema,Concepto,funciona,concepto_estandar,impacto,inter_local,DescxErrores
0,1.00,http://ep00.epimg.net/rss/tags/ultimas_noticia...,esp,el pais,venezuela,ultimo,Últimas noticias,NaN,actualidad,3,NaN,0
1,2.00,http://ep00.epimg.net/rss/tags/noticias_mas_vi...,esp,el pais,venezuela,más leido,Noticias más vistas,NaN,actualidad,6,NaN,0
2,3.00,http://ep00.epimg.net/rss/economia/portada.xml,esp,el pais,colombia,economía,Portada de Economía,NaN,economía,10,NaN,0
3,4.00,https://www.clarin.com/rss/lo-ultimo/,esp,el clarín,argentina,lo-ultimo,"Home, lo último",NaN,actualidad,6,NaN,0
4,5.00,https://www.clarin.com/rss/economia/,esp,el clarín,argentina,economia,Economía,NaN,economía,10,NaN,0

In [10]:
df_Tweets = pd.read_excel (r'backupT.xlsx', sheet_name='Hoja7')

In [11]:
df_Tweets.head()

                      id          created_at lang     id_fuente  polaridad
0 1314979717343252480.00 2020-10-10 17:22:50  esp  elespectador      -0.29
1 1314688950330683392.00 2020-10-09 22:07:26  esp  elespectador      -0.29
2 1321150361344839680.00 2020-10-27 18:02:46  esp  elespectador      -0.29
3 1321540918999195648.00 2020-10-28 19:54:42  esp  elespectador      -0.29
4 1325468437276192768.00 2020-11-08 16:01:16  esp  elespectador      -0.29

In [12]:
df_Base_Tweets = pd.read_excel (r'backupT.xlsx', sheet_name='Hoja2')

In [13]:
df_Base_Tweets.head()

,screen_name,id,id_str,name,location,Idioma,concepto,impacto,NoTweets
0,bbcmundo,10012122,10012122,BBC News Mundo,"bLondres, Inglaterra.",esp,internacional,8,200
1,BluRadioCo,622082899,622082899,BluRadio Colombia,"bBogot\xc3\xa1, D.C., Colombia",esp,actualidad,8,400
2,elespectador,14834302,14834302,elespectador,"bBogot\xc3\xa1, Colombia",esp,actualidad,8,450
3,RevistaSemana,18079284,18079284,Revista Semana,bColombia,esp,actualidad,8,350
4,ELTIEMPO,9633802,9633802,EL TIEMPO,"bBogot\xc3\xa1, Colombia",esp,actualidad,8,200

In [14]:
### Carga de TRM
#df_trm=pd.read_csv(ubicacion, sep=';',encoding = "ISO-8859-1", engine='python', decimal=",")
trm_df=pd.read_csv('TRM2020.csv', sep=';',encoding = "ISO-8859-1", engine='python', decimal=",")

In [15]:
trm_df['date']=pd.to_datetime(trm_df['date'])

In [16]:
#trm_df.set_index('date',inplace=True)

In [17]:
trm_df.head(10)

,Fecha,fecha_Operación,TRM,Diferencia,Dia sem,nom Dia Sem,fin Semana,Dif Cero,date
0,31/05/2020,30/05/2020,3718.82,0.00,7,sáb,1,1,2020-05-30
1,1/06/2020,31/05/2020,3718.82,0.00,1,dom,1,1,2020-05-31
2,2/06/2020,1/06/2020,3716.35,-2.47,2,lun,0,0,2020-06-01
3,3/06/2020,2/06/2020,3651.42,-64.93,3,mar,0,0,2020-06-02
4,4/06/2020,3/06/2020,3588.89,-62.53,4,mié,0,0,2020-06-03
5,5/06/2020,4/06/2020,3597.47,8.58,5,jue,0,0,2020-06-04
6,6/06/2020,5/06/2020,3565.06,-32.41,6,vie,0,0,2020-06-05
7,7/06/2020,6/06/2020,3565.06,0.00,7,sáb,1,1,2020-06-06
8,8/06/2020,7/06/2020,3565.06,0.00,1,dom,1,1,2020-06-07
9,9/06/2020,8/06/2020,3599.00,33.94,2,lun,0,0,2020-06-08

In [18]:
trm_df['date_ini']=trm_df['date']
trm_df['date_fin']=trm_df['date']

In [19]:
flag=0
for index, row in trm_df.iterrows():
    if row['Dif Cero'] == 1 :
        if flag==0 :
            index_ini=index
            flag=1
    else :        
        if flag==1:
            dia_fin=row['date']
            index_fin=index
            flag=0
            #trm_df[trm_df['date'].between(dia_ini,dia_fin)]['date_fin']=dia_fin
            for i in range(index_ini,index_fin+1):
                #print(i,dia_fin)
                trm_df.loc[i,'date_fin']=dia_fin

In [20]:
calendario=trm_df[['date','date_fin']]
calendario.head(10)

        date   date_fin
0 2020-05-30 2020-06-01
1 2020-05-31 2020-06-01
2 2020-06-01 2020-06-01
3 2020-06-02 2020-06-02
4 2020-06-03 2020-06-03
5 2020-06-04 2020-06-04
6 2020-06-05 2020-06-05
7 2020-06-06 2020-06-08
8 2020-06-07 2020-06-08
9 2020-06-08 2020-06-08

In [21]:
calendario.dtypes

date        datetime64[ns]
date_fin    datetime64[ns]
dtype: object

### Resumir fuentes con medianas

#### Quitar Cero

In [22]:
df_Rss=df_Rss[df_Rss['polaridad']!=0]

In [23]:
df_Rss['dateF']=pd.to_datetime(df_Rss['date']).dt.date

In [24]:
df_Rss['dateF']=pd.to_datetime(df_Rss['dateF'])

In [25]:
df_Rss.head(10)

,fuenteRss,idP,date,polaridad,dateF
10991,http://www.eltiempo.com/rss/mundo_medio-orient...,https://www.eltiempo.com/mundo/medio-oriente/i...,2020-09-11 16:20:15,-0.76,2020-09-11
10992,http://www.eltiempo.com/rss/mundo_asia.xml,https://www.eltiempo.com/mundo/asia/coronaviru...,2020-10-06 02:30:41,-0.86,2020-10-06
10993,http://www.eltiempo.com/rss/mundo_asia.xml,https://www.eltiempo.com/mundo/asia/policias-s...,2020-10-04 10:25:47,-0.95,2020-10-04
10994,http://www.eltiempo.com/rss/mundo_asia.xml,https://www.eltiempo.com/mundo/asia/china-por-...,2020-10-02 05:08:52,0.09,2020-10-02
10995,http://www.eltiempo.com/rss/mundo_asia.xml,https://www.eltiempo.com/mundo/asia/que-puede-...,2020-10-01 23:47:38,-0.78,2020-10-01
10996,http://www.eltiempo.com/rss/mundo_asia.xml,https://www.eltiempo.com/mundo/asia/como-reduc...,2020-10-01 18:22:44,-0.84,2020-10-01
10997,http://www.eltiempo.com/rss/mundo_asia.xml,https://www.eltiempo.com/mundo/asia/onu-cita-a...,2020-09-29 14:48:24,0.11,2020-09-29
10998,http://www.eltiempo.com/rss/mundo_asia.xml,https://www.eltiempo.com/mundo/asia/se-intensi...,2020-09-29 04:32:15,-0.60,2020-09-29
10999,http://www.eltiempo.com/rss/mundo_asia.xml,https://www.eltiempo.com/mundo/asia/la-policia...,2020-09-26 19:12:59,-1.00,2020-09-26
11000,http://www.eltiempo.com/rss/mundo_asia.xml,https://www.eltiempo.com/mundo/asia/corea-del-...,2020-09-25 15:25:19,-0.37,2020-09-25

In [26]:
df_Rss.dtypes

fuenteRss            object
idP                  object
date         datetime64[ns]
polaridad           float64
dateF        datetime64[ns]
dtype: object

In [27]:
df_Rss=df_Rss.merge(calendario, left_on='dateF', right_on='date', how='left')

In [28]:
df_Tweets.head(10)

                      id          created_at lang     id_fuente  polaridad
0 1314979717343252480.00 2020-10-10 17:22:50  esp  elespectador      -0.29
1 1314688950330683392.00 2020-10-09 22:07:26  esp  elespectador      -0.29
2 1321150361344839680.00 2020-10-27 18:02:46  esp  elespectador      -0.29
3 1321540918999195648.00 2020-10-28 19:54:42  esp  elespectador      -0.29
4 1325468437276192768.00 2020-11-08 16:01:16  esp  elespectador      -0.29
5 1325105260843704320.00 2020-11-07 15:58:08  esp  elespectador      -0.29
6 1324742651141345280.00 2020-11-06 15:57:15  esp  elespectador      -0.29
7 1324900640838053888.00 2020-11-07 02:25:02  esp  elespectador      -0.29
8 1323373468231061504.00 2020-11-02 21:16:36  esp  elespectador      -0.29
9 1326156906189221888.00 2020-11-10 13:36:59  esp  elespectador      -0.29

In [29]:
df_Tweets=df_Tweets[df_Tweets['polaridad']!=0]

In [30]:
df_Tweets['dateF']=pd.to_datetime(df_Tweets['created_at']).dt.date
df_Tweets['dateF']=pd.to_datetime(df_Tweets['dateF'])

In [31]:
df_Tweets=df_Tweets.merge(calendario, left_on='dateF', right_on='date', how='left')

##### Describir Bases

In [32]:
df_Rss['polaridad'].describe()

count   117826.00
mean        -0.26
std          0.61
min         -1.00
25%         -0.83
50%         -0.42
75%          0.32
max          1.00
Name: polaridad, dtype: float64

In [33]:
df_Tweets['polaridad'].describe()

count   539872.00
mean        -0.46
std          0.50
min         -1.00
25%         -0.87
50%         -0.62
75%         -0.15
max          1.00
Name: polaridad, dtype: float64

## Manejo de fechas sin operaciones

In [34]:
#dias_sin_operacion.head()

¿correlacionan mejor sin contar los días sin operación?

In [35]:
trm_df.head(20)

,Fecha,fecha_Operación,TRM,Diferencia,Dia sem,nom Dia Sem,fin Semana,Dif Cero,date,date_ini,date_fin
0,31/05/2020,30/05/2020,3718.82,0.00,7,sáb,1,1,2020-05-30,2020-05-30,2020-06-01
1,1/06/2020,31/05/2020,3718.82,0.00,1,dom,1,1,2020-05-31,2020-05-31,2020-06-01
2,2/06/2020,1/06/2020,3716.35,-2.47,2,lun,0,0,2020-06-01,2020-06-01,2020-06-01
3,3/06/2020,2/06/2020,3651.42,-64.93,3,mar,0,0,2020-06-02,2020-06-02,2020-06-02
4,4/06/2020,3/06/2020,3588.89,-62.53,4,mié,0,0,2020-06-03,2020-06-03,2020-06-03
5,5/06/2020,4/06/2020,3597.47,8.58,5,jue,0,0,2020-06-04,2020-06-04,2020-06-04
6,6/06/2020,5/06/2020,3565.06,-32.41,6,vie,0,0,2020-06-05,2020-06-05,2020-06-05
7,7/06/2020,6/06/2020,3565.06,0.00,7,sáb,1,1,2020-06-06,2020-06-06,2020-06-08
8,8/06/2020,7/06/2020,3565.06,0.00,1,dom,1,1,2020-06-07,2020-06-07,2020-06-08
9,9/06/2020,8/06/2020,3599.00,33.94,2,lun,0,0,2020-06-08,2020-06-08,2020-06-08
10,10/06/2020,9/06/2020,3643.02,44.02,3,mar,0,0,2020-06-09,2020-06-09,2020-06-09
11,11/06/2020,10/06/2020,3674.81,31.79,4,mié,0,0,2020-06-10,2020-06-10,2020-06-10
12,12/06/2020,11/06/2020,3746.46,71.65,5,jue,0,0,2020-06-11,2020-06-11,2020-06-11
13,13/06/2020,12/06/2020,3758.15,11.69,6,vie,0,0,2020-06-12,2020-06-12,2020-06-12
14,14/06/2020,13/06/2020,3758.15,0.00,7,sáb,1,1,2020-06-13,2020-06-13,2020-06-16
15,15/06/2020,14/06/2020,3758.15,0.00,1,dom,1,1,2020-06-14,2020-06-14,2020-06-16
16,16/06/2020,15/06/2020,3758.15,0.00,2,lun,0,1,2020-06-15,2020-06-15,2020-06-16
17,17/06/2020,16/06/2020,3741.88,-16.27,3,mar,0,0,2020-06-16,2020-06-16,2020-06-16
18,18/06/2020,17/06/2020,3749.03,7.15,4,mié,0,0,2020-06-17,2020-06-17,2020-06-17
19,19/06/2020,18/06/2020,3760.22,11.19,5,jue,0,0,2020-06-18,2020-06-18,2020-06-18

#### Agrupación fuente día

In [36]:
res_Rss=df_Rss.groupby(['fuenteRss','date_fin'])['polaridad'].median()
res_Rss=res_Rss.to_frame()
res_Rss.reset_index(inplace=True)

In [37]:
res_Rss.head(10)

                        fuenteRss   date_fin  polaridad
0  http://elnacional.com.do/feed/ 2020-10-13      -0.84
1  http://elnacional.com.do/feed/ 2020-10-26      -0.88
2  http://elnacional.com.do/feed/ 2020-10-27      -0.93
3  http://elnacional.com.do/feed/ 2020-10-28      -0.93
4  http://elnacional.com.do/feed/ 2020-10-29      -0.95
5  http://elnacional.com.do/feed/ 2020-10-30      -0.87
6  http://elnacional.com.do/feed/ 2020-11-03      -0.75
7  http://elnacional.com.do/feed/ 2020-11-04      -0.92
8  http://elnacional.com.do/feed/ 2020-11-05      -0.95
9  http://elnacional.com.do/feed/ 2020-11-06      -0.88

In [38]:
df_Tweets.head(2)

,id,created_at,lang,id_fuente,polaridad,dateF,date,date_fin
0,1314979717343252480.00,2020-10-10 17:22:50,esp,elespectador,-0.29,2020-10-10,2020-10-10,2020-10-13
1,1314688950330683392.00,2020-10-09 22:07:26,esp,elespectador,-0.29,2020-10-09,2020-10-09,2020-10-09

In [39]:
res_Tweets=df_Tweets.groupby(['id_fuente','date_fin'])['polaridad'].median()
res_Tweets=res_Tweets.to_frame()
res_Tweets.reset_index(inplace=True)

In [40]:
res_Tweets.head(10)

    id_fuente   date_fin  polaridad
0  BluRadioCo 2020-10-09      -0.58
1  BluRadioCo 2020-10-13      -0.52
2  BluRadioCo 2020-10-26      -0.52
3  BluRadioCo 2020-10-27      -0.54
4  BluRadioCo 2020-10-28      -0.66
5  BluRadioCo 2020-10-29      -0.49
6  BluRadioCo 2020-10-30      -0.46
7  BluRadioCo 2020-11-03      -0.47
8  BluRadioCo 2020-11-04      -0.56
9  BluRadioCo 2020-11-05      -0.50

###  revisar rangos de fechas dataSets

In [41]:
print('res_Rss',res_Rss['date_fin'].min(),res_Rss['date_fin'].max())
print('res_Tweets',res_Tweets['date_fin'].min(),res_Tweets['date_fin'].max())
print('trm_df',trm_df['date_fin'].min(),trm_df['date_fin'].max())

res_Rss 2020-06-01 00:00:00 2021-06-15 00:00:00
res_Tweets 2020-10-05 00:00:00 2021-06-15 00:00:00
trm_df 2020-06-01 00:00:00 2021-06-20 00:00:00

In [42]:
res_Rss=res_Rss[(res_Rss['date_fin']>='2020-10-15')&(res_Rss['date_fin']<='2021-06-15')]

In [43]:
res_Rss=res_Rss.merge(trm_df[['date','Diferencia']],left_on='date_fin', right_on='date', how='left')

In [44]:
res_Rss.head()

                        fuenteRss   date_fin  polaridad       date  Diferencia
0  http://elnacional.com.do/feed/ 2020-10-26      -0.88 2020-10-26       30.16
1  http://elnacional.com.do/feed/ 2020-10-27      -0.93 2020-10-27       -2.59
2  http://elnacional.com.do/feed/ 2020-10-28      -0.93 2020-10-28       31.23
3  http://elnacional.com.do/feed/ 2020-10-29      -0.95 2020-10-29        8.07
4  http://elnacional.com.do/feed/ 2020-10-30      -0.87 2020-10-30        9.03

In [45]:
res_Tweets=res_Tweets[(res_Tweets['date_fin']>='2020-10-15')&(res_Tweets['date_fin']<='2021-06-15')]

In [46]:
res_Tweets=res_Tweets.merge(trm_df[['date','Diferencia']],left_on='date_fin', right_on='date', how='left')

In [48]:
res_Tweets.head()

    id_fuente   date_fin  polaridad       date  Diferencia
0  BluRadioCo 2020-10-26      -0.52 2020-10-26       30.16
1  BluRadioCo 2020-10-27      -0.54 2020-10-27       -2.59
2  BluRadioCo 2020-10-28      -0.66 2020-10-28       31.23
3  BluRadioCo 2020-10-29      -0.49 2020-10-29        8.07
4  BluRadioCo 2020-10-30      -0.46 2020-10-30        9.03

###  Tablas correlacion

In [52]:
res_Rss_resultados=res_Rss[['fuenteRss']].value_counts().to_frame()

In [63]:
corr_Rss=res_Rss.groupby('fuenteRss')[['polaridad','Diferencia']].corr()

In [64]:
corr_Rss.reset_index(inplace=True)
corr_Rss=corr_Rss[corr_Rss['level_1']=='Diferencia']
corr_Rss.drop(columns=['Diferencia','level_1'], inplace=True)

In [74]:
res_Rss_resultados=res_Rss_resultados.merge(corr_Rss, left_on='fuenteRss', right_on='fuenteRss', how='left')

In [76]:
res_Rss_resultados.columns=['fuenteRss','cuenta','corr']

In [84]:
res_Rss_resultados.sort_values('corr')

                                             fuenteRss  cuenta  corr
115  http://www.portafolio.co/rss/economia/infraest...       5 -0.95
116   http://portafolio.co/rss/negocios/emprendimiento       4 -0.63
97     http://www.nydailynews.com/cmlink/NYDN.News.rss      18 -0.55
96   http://www.nydailynews.com/cmlink/NYDN.News.Wo...      18 -0.45
90            https://www.reforma.com/rss/justicia.xml      24 -0.34
89    http://feeds.washingtonpost.com/rss/rss_blogpost      24 -0.32
57           http://feeds.washingtonpost.com/rss/world      98 -0.30
88               http://www.portafolio.co/rss/negocios      26 -0.29
84              http://www.reforma.com/rss/portada.xml      29 -0.28
75       https://www.eltiempo.com/rss/mundo_africa.xml      50 -0.26
65   http://feeds.washingtonpost.com/rss/rss_powerpost      92 -0.23
10   https://www.eltiempo.com/rss/mundo_latinoameri...     147 -0.20
53   http://feeds.washingtonpost.com/rss/rss_mornin...     103 -0.18
43   https://www.eltiempo.com/rss/economia_finanzas...     117 -0.15
80                      http://elnacional.com.do/feed/      29 -0.15
18   http://www.nytimes.com/services/xml/rss/nyt/Me...     144 -0.14
8    http://www.nytimes.com/services/xml/rss/nyt/NY...     148 -0.14
4    http://www.nytimes.com/services/xml/rss/nyt/Wo...     150 -0.14
92   http://www.nydailynews.com/cmlink/NYDN.News.Na...      20 -0.13
40           https://www.eltiempo.com/rss/colombia.xml     118 -0.13
109  http://www.eltiempo.com/rss/economia_sector-fi...      12 -0.13
74           https://www.eltiempo.com/rss/politica.xml      52 -0.12
73       https://www.portafolio.co/rss/economia/empleo      54 -0.12
87      http://www.portafolio.co/rss/negocios/empresas      26 -0.12
27    https://www.nydailynews.com/cmlink/NYDN.News.rss     131 -0.12
66      http://feeds.washingtonpost.com/rss/rss_digger      90 -0.12
103           http://www.eltiempo.com/rss/colombia.xml      16 -0.11
67   http://www.nytimes.com/services/xml/rss/nyt/Sm...      76 -0.11
14   http://ep00.epimg.net/rss/tags/ultimas_noticia...     145 -0.11
63   https://www.eltiempo.com/rss/mundo_medio-orien...      93 -0.11
55           https://www.eltiempo.com/rss/economia.xml     101 -0.11
30         https://www.eltiempo.com/rss/tecnosfera.xml     130 -0.10
82             http://www.reforma.com/rss/justicia.xml      29 -0.10
69   http://www.nytimes.com/services/xml/rss/nyt/Yo...      71 -0.10
29       https://www.eltiempo.com/rss/mundo_europa.xml     130 -0.10
78   https://portafolio.co/rss/negocios/emprendimiento      44 -0.10
12   http://www.nytimes.com/services/xml/rss/nyt/US...     147 -0.10
7    http://rssfeeds.usatoday.com/usatoday-NewsTopS...     149 -0.10
62   http://feeds.washingtonpost.com/rss/rss_monkey...      93 -0.09
70     https://www.portafolio.co/rss/economia/gobierno      69 -0.09
85               http://www.portafolio.co/rss/economia      28 -0.09
71   http://feeds.washingtonpost.com/rss/rss_fact-c...      67 -0.09
11          http://www.portafolio.co/rss/internacional     147 -0.09
58        http://feeds.washingtonpost.com/rss/national      98 -0.09
13         https://feeds.a.dj.com/rss/RSSLifestyle.xml     147 -0.09
17       https://feeds.a.dj.com/rss/RSSMarketsMain.xml     144 -0.09
34                              http://nypost.com/feed     127 -0.08
42       https://www.reforma.com/rss/internacional.xml     117 -0.08
72   https://www.portafolio.co/rss/economia/infraes...      56 -0.07
76           http://feeds.nytimes.com/nyt/rss/Business      49 -0.07
50   https://www.eltiempo.com/rss/economia_sector-f...     107 -0.07
19   http://rssfeeds.usatoday.com/UsatodaycomNation...     142 -0.06
48             https://www.reforma.com/rss/portada.xml     111 -0.06
47     https://www.portafolio.co/rss/negocios/empresas     112 -0.06
31   https://www.nydailynews.com/cmlink/NYDN.News.P...     130 -0.06
0    http://www.nytimes.com/services/xml/rss/nyt/Ho...     155 -0.06
51              https://www.portafolio.co/rss/negocios     106 -0.04
24                https://www.clarin.com/rss/economia/     136 -0.04
108  http://www.eltiempo.com/rss/economia_finanzas-...      13 -0.04
46              https://www.eltiempo.com/rss/mundo.xml     115 -0.04
77                    http://nypost.com/business/feed/      48 -0.03
61     http://feeds.washingtonpost.com/rss/rss_the-fix      96 -0.03
32   https://www.nydailynews.com/cmlink/NYDN.News.W...     129 -0.03
44            http://www.elcomercio.com/rss/actualidad     117 -0.02
93      http://www.portafolio.co/rss/economia/finanzas      19 -0.02
39            https://www.eltiempo.com/rss/cultura.xml     118 -0.02
95    https://www.portafolio.co/rss/economia/impuestos      18 -0.01
26                       http://www.elcomercio.com/rss     134 -0.01
36               https://www.clarin.com/rss/lo-ultimo/     122 -0.01
22                         http://nypost.com/news/feed     138 -0.01
112         http://www.eltiempo.com/rss/mundo_asia.xml       9 -0.01
21      http://ep00.epimg.net/rss/economia/portada.xml     138 -0.01
68               http://portafolio.co/rss/mis-finanzas      72 -0.00
60        http://feeds.washingtonpost.com/rss/politics      97  0.00
79                 http://portafolio.co/rss/innovacion      32  0.00
52          http://feeds.washingtonpost.com/rss/sports     103  0.01
64   http://feeds.washingtonpost.com/rss/national/e...      92  0.01
56                   https://nypost.com/business/feed/     100  0.02
59     https://www.portafolio.co/rss/economia/finanzas      97  0.02
106       http://www.eltiempo.com/rss/mundo_europa.xml      14  0.02
2          http://feeds.nytimes.com/nyt/rss/Technology     153  0.03
37           https://www.eltiempo.com/rss/deportes.xml     120  0.05
38         https://www.eltiempo.com/rss/mundo_asia.xml     120  0.05
54          https://feeds.nytimes.com/nyt/rss/Business     102  0.05
15   http://www.nytimes.com/services/xml/rss/nyt/Ec...     145  0.05
23         https://feeds.a.dj.com/rss/RSSWorldNews.xml     137  0.05
9      https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml     148  0.06
49              https://www.portafolio.co/rss/economia     110  0.07
5    http://www.nytimes.com/services/xml/rss/nyt/Sp...     150  0.07
16   https://www.eltiempo.com/rss/mundo_eeuu-y-cana...     144  0.07
98      http://www.portafolio.co/rss/economia/gobierno      18  0.08
81             http://www.reforma.com/rss/negocios.xml      29  0.08
28   https://www.nydailynews.com/cmlink/NYDN.News.C...     131  0.08
20           https://www.eltiempo.com/rss/justicia.xml     139  0.09
3               https://feeds.a.dj.com/rss/RSSWSJD.xml     151  0.09
45            https://www.reforma.com/rss/negocios.xml     116  0.10
83        http://www.reforma.com/rss/internacional.xml      29  0.11
6            https://feeds.a.dj.com/rss/RSSOpinion.xml     149  0.11
41   https://www.eltiempo.com/rss/economia_empresas...     117  0.11
35   http://www.nytimes.com/services/xml/rss/nyt/En...     124  0.11
25   https://www.nydailynews.com/cmlink/NYDN.News.N...     135  0.11
101              http://www.eltiempo.com/rss/mundo.xml      16  0.12
111           http://www.eltiempo.com/rss/economia.xml      11  0.12
105     http://portafolio.co/rss/mis-finanzas/vivienda      14  0.12
1    http://www.nytimes.com/services/xml/rss/nyt/Sc...     153  0.12
33   https://www.eltiempo.com/rss/economia_sectores...     128  0.16
113       http://www.portafolio.co/rss/economia/empleo       8  0.16
86   http://feeds.washingtonpost.com/rss/rss_innova...      27  0.17
91   http://www.nydailynews.com/cmlink/NYDN.News.Po...      20  0.17
100           http://www.eltiempo.com/rss/deportes.xml      16  0.18
107  http://www.eltiempo.com/rss/economia_empresas.xml      14  0.20
110       https://portafolio.co/rss/negocios/inversion      12  0.21
117  http://www.eltiempo.com/rss/mundo_medio-orient...       3  0.24
94   http://www.nydailynews.com/cmlink/NYDN.News.Cr...      18  0.24
102  http://www.eltiempo.com/rss/economia_sectores.xml      16  0.32
99          http://www.eltiempo.com/rss/tecnosfera.xml      17  0.43
104            http://www.eltiempo.com/rss/cultura.xml      16  0.64
114       http://portafolio.co/rss/mis-finanzas/ahorro       5  0.93

In [53]:
res_Tweets_resultados=res_Tweets[['id_fuente']].value_counts().to_frame()

In [70]:
corr_Tweets=res_Tweets.groupby('id_fuente')[['polaridad','Diferencia']].corr()

In [71]:
corr_Tweets.reset_index(inplace=True)
corr_Tweets=corr_Tweets[corr_Tweets['level_1']=='Diferencia']
corr_Tweets.drop(columns=['Diferencia','level_1'], inplace=True)

In [81]:
res_Tweets_resultados=res_Tweets_resultados.merge(corr_Tweets, left_on='id_fuente', right_on='id_fuente', how='left')
res_Tweets_resultados.columns=['id_fuente','cuenta','corr']

In [83]:
res_Tweets_resultados.sort_values('corr')

          id_fuente  cuenta  corr
9           NBCNews     146 -0.16
17    PublimetroCol     143 -0.11
16       MailOnline     144 -0.10
12            NTN24     145 -0.08
11  NoticiasCaracol     145 -0.07
6          bbcmundo     147 -0.07
2       NoticiasRCN     149 -0.06
1          rcnradio     149 -0.03
0              NASA     151 -0.01
18         rcnmundo     142  0.00
10     CaracolRadio     145  0.02
13        clarincom     145  0.02
5      elcolombiano     147  0.04
8        BluRadioCo     146  0.05
4     RevistaSemana     148  0.06
3              lafm     148  0.06
7     RevistaDinero     146  0.08
14     elespectador     145  0.11
15         ELTIEMPO     145  0.14

###  Validar Correlaciones

# Pasos a Seguir
3. Validar correlación con Lags
4. Validar correlacion spearman